name: Build and Package

on:
  push:
    branches:
      - main
  # tags:
  #   - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Environment
      run: |
        sudo apt-get update
        sudo apt-get install zip -y

    - name: Prepare Release Directory
      run: |
        mkdir -p release/mwse/mods/clone
        cp -r meshes release/
        cp *.toml release/
        cp *.ESP release/
        cp *.omwscripts release/
        cp -r scripts release/
        cp -r scripts release/mwse/mods/clone/
        mv *.lua release/mwse/mods/clone/

    - name: Zip Release
      run: |
        cd release
        zip -r ../my_project.zip .

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: my_project
        path: my_project.zip